# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2bd1b0331e94d8b0a05247a1ea3a348076cd1b9921527c6df21c1ea029373595b19858130ea4af0e80e2c66b20b85dab3acce69b419b59e259cac955e0d6b90

test:
  secret_key_base: 6294d2a94e7f8ef4e35437e19782dba8f4b932a3ab9a42a23efa18461114dd587ddad5c2c08ea383e751aefdc72ddd900100b36eae31aeeef3a4f528bda0d74f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
